### ISSUE TITLE
Understanding the dimension ncell in a layer

### ISSUE THREAD

**Issue by cazaudo** [barryrowlingson/trmm#1]
Hi, 

based on your codes , I get the following variable prec

h=get_header("C:/Users/Asus/Desktop/ENSTA/RainData/3B40RT.2012090100.7R2.bin")
prec = get_layer(h,"precipitation")

(the bin file can be downloaded from ftp://trmmopen.gsfc.nasa.gov/pub/merged/3B41RT/2011/01/) , but I do not understand to what corresponds its dimension nb_cell , 

> prec
> class       : RasterLayer 
> dimensions  : 720, 1440, 1036800  (nrow, ncol, ncell)
> resolution  : 0.25, 0.25  (x, y)
> extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
> coord. ref. : +init=epsg:4326 
> data source : in memory
> names       : layer 
> values      : -34.98, 45.05  (min, max)

Thank you !
Dorian Cazau

**Comment by barryrowlingson** [comment]
I don't see `nb_cell` anywhere, so I'm not sure what you mean by that. `prec` is a single layer raster, which is 720x1440 cells, which is a total of 1036800 cells. Apart from that I don't think there's any more information...

Source data file referenced seems to be in a different folder, here:
ftp://trmmopen.gsfc.nasa.gov/pub/merged/3B40RT/2012/09/3B40RT.2012090100.7R2.bin.gz

**Comment by cazaudo** [comment]
OK thank you for this help , but actually the function I was missing was 

PrecMatrix=as.matrix(prec, mode='any')

to convert a layer into a matrix , that is why I did not understand this variable nb_cell ...

**Comment by barryrowlingson** [comment]
I still don't understand what you are talking about with reference to `nb_cell`. I have not seen `nb_cell` anywhere. Is it in an error message? In some code? Where? Why do you care? What are you trying to do?

That line works fine for me:

`> PrecMatrix=as.matrix(prec, mode='any')`

so I'm no nearer understanding your problem.
