### ISSUE TITLE
Issue about 'ncdf' package

### ISSUE THREAD

**Issue by mjwang1010** [barryrowlingson/trmm#2]
Hi, when I tried to install this package on my macbook, it seemed that the 'ncdf' package was unavailable, so that, the installing trmm failed. The code is like this:
"
Downloading GitHub repo barryrowlingson/trmm@master
from URL https://api.github.com/repos/barryrowlingson/trmm/zipball/master
Installing trmm
Skipping 1 unavailable package: ncdf
'/Library/Frameworks/R.framework/Resources/bin/R'  \
  --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  '/private/var/folders/72/c2_s7d6x48dc5vz5853_gtf80000gn/T/RtmpvnS21c/devtools959577157942/barryrowlingson-trmm-f6c7858'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

ERROR: dependency ‘ncdf’ is not available for package ‘trmm’
- removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/trmm’
  Error: Command failed (1)

"

R is using 'ncdf4' instead of 'ncdf'.

**Comment by barryrowlingson** [comment]
I've just pushed a new version that should work with ncdf4 - all that seems to have happened is the functions have different names! I haven't done any extensive testing so let me know if it works for you.

**Comment by mjwang1010** [comment]
Thanks! Yeah, it worked. I have already installed the package successfully and tried the example. Actually, one more package 'colorspace' need to be installed before plotting. Otherwise, it turns out to be an error like this (at least on my machine):
"Error in as.double(y) : 
  cannot coerce type 'S4' to vector of type 'double'"

**Comment by barryrowlingson** [comment]
I think plotting requires `raster` which probably requires `colorspace`. I'll open a new PR for that.
